data:
  path: ../libero_dataset/libero_goal
  handler: read_libero
  train_split: 1.0
  multiplier: 40
  seed: 114514
  seg_len: 60
  init_mode: train
  loss_modes:
  - 2
  - 2
  - 1

model:
  dropout: 0.0
  n_embd: 256
  n_head: 8
  encoder:
    n_layer: 12
    use_causal: false
    hyper_dim: ~
  reconstructor:
    n_layer: 8
    use_causal: false
    hyper_dim: ~
  next:
    n_layer: 8
    use_causal: false
    hyper_dim: ~
  goal:
    n_layer: 8
    use_causal: true
    hyper_dim: 256
  th_config: 1000
  modal_usage: [1, 1, 1]
  
train:
  n_iters: 200_000
  batch_size: 1 # 256 # 512
  init_lr: 0.001
  weight_decay: 0.001
  beta1: 0.9
  beta2: 0.95
  lr_schedule: cos_decay_with_warmup
  t_warmup: 100
  save_ckpt_every: 10 # 10_000
  log_every: 10
  num_workers: 6
  
  coes:
    enc: "1.0"
    th: "1.0"
    now: "1.0"
    goal: "1.0"
